### PR TITLE
Use andrew-codes/playnite-web-app image for HASS addon

### PR DESCRIPTION
**Pull request by cvele**
Given that playnite-web-app supports linux/arm64 now (judging from the manifest), let's use it directly in HASS addon.

Bumped version to `8.2.1`, created #557 to automate this.

### CODE REVIEW

**Comment by andrew-codes** [comment]
Hi. Thanks for the contribution. Does the hass add on not need the functionality from the [run.sh](https://github.com/andrew-codes/playnite-web/blob/main/hass-playnite-web/src/run.sh) file? If not, then let's also remove it and it's related code in the same PR. I'm thinking these also should be included in the removal:

- [ ] Docker file
- [ ] Scripts used to package and publish the docker file. 
- [ ] src directory

This is all assuming it is all dead code now. I can try to update the PR, but won't be able to until I'm back in town. However, feel free and empowered to do so also and I'll merge once done.

I actually thought it was automatically incremented the version and released, but I just realized this is not happening automatically. Thank you for opening the other issue. We can track that functionality in that issue. 

Thanks again!

**Comment by andrew-codes** [comment]
I also think it makes sense to lock down the image tag to a specific version. This eliminates the possibility of the config's version and the image version from being different. We can automate the process of updating the image tag in the issue's body of work.

**Comment by cvele** [comment]
@andrew-codes You are absolutely correct! I guess I was overeager to get it to work that it blind-sighted me. I'll refocus on pipeline which should be building it automatically as version is going up. Closing this pr.

**Comment by andrew-codes** [comment]
@cvele , do we still need the separate docker image to include the `src` directory's bash script, or is that no longer needed? I'm not as familiar with HASS add-ons, so it isn't clear to me if the code is still relevant once the versioning aspect is corrected. Leaning on your expertise here. Thanks!

**Pull request closed without merging**
