### PR TITLE
Multiarch Playnite Web Docker Images

### PR DESCRIPTION
**Pull request by cvele**
WIP

Goal is to release Docker images supporting multiple architectures, primarily `arm64`. While this is not a blocker for #319 it's one for personal use-case.

### CODE REVIEW

**Comment by cvele** [comment]
Yarn publish target has been updated to build for all available architectures by inspecting engine on runtime: `docker buildx inspect --bootstrap | awk -F 'Platforms: ' '{if (NF>1) print $2}'``

Github Actions have been updated so that they setup QEMU and configure it for `amd64`, `arm64`.

**Comment by cvele** [comment]
@andrew-codes Can you provide some guidance on how to best test these changes?

**Comment by andrew-codes** [comment]
Based on the new error message, I think the remaining work is to enable multi-arch builds on the runner; specifically, enabling the containerd image store on the runner. It is not clear to me what I need to do to accomplish this, so any advice or guidance is appreciated. Thanks for your contribution!

**Comment by andrew-codes** [comment]
Feel free to revert the commit: https://github.com/andrew-codes/playnite-web/pull/326/commits/0fa413d99518b29df248d828e539b0369ae53e52. I am taking care of that in a separate PR now.

**Comment by cvele** [comment]
Reverted: `0fa413d99518b29df248d828e539b0369ae53e52`

Additionally added some parameters to Buildx setup which should enable the containerd image store which supports multi-platform builds.

**Comment by andrew-codes** [comment]
I'm not familiar with the [error in the build](https://github.com/andrew-codes/playnite-web/actions/runs/9281113159/job/25667887315?pr=326#step:13:112). @cvele , let me know how I can support in resolving this. Thanks!

**Comment by andrew-codes** [comment]
Also, I mis-spoke, I am not using a custom runner image in this repo. I can re-run the PR once the current error is updated. Thanks!

**Pull request merged**
